version: '3.9'
services:
  apache:
    build: .
    container_name: apache
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./conf/example.conf:/etc/apache2/sites-enabled/000-default.conf
    - ./public_html:/var/www/example.com/public_html
    - ./certs:/etc/apache2/certs:ro
